### ISSUE TITLE
[FABRIC - BUG] Not filled all elements of the vertex

### ISSUE THREAD

**Issue by ExoPlant** [nicguzzo/wands#17]
On right clicking with the 'Line' mode it produces this error:
```
java.lang.IllegalStateException: Not filled all elements of the vertex
	at net.minecraft.class_287.method_1344(class_287.java:281) ~[client-intermediary.jar:?]
	at net.nicguzzo.wands.ClientRender.player_facing_line(ClientRender.java:892) ~[BuildingWands-2.3.2_mc1.18.1-fabric.jar:?]
	at net.nicguzzo.wands.ClientRender.preview_mode(ClientRender.java:592) ~[BuildingWands-2.3.2_mc1.18.1-fabric.jar:?]
	at net.nicguzzo.wands.ClientRender.render(ClientRender.java:220) ~[BuildingWands-2.3.2_mc1.18.1-fabric.jar:?]
	at net.minecraft.class_761.handler$bfk000$renderLevel(class_761.java:6889) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_22710(class_761.java:1563) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:1031) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:811) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1117) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:733) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:238) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.12.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
```
It's 1.18, fabric loader is showed in the log above

**Comment by nicguzzo** [comment]
fixing it right now, I forgot to update the Line mode rendering method.

**Comment by nicguzzo** [comment]
fixed
