### ISSUE TITLE
[Fabric] Crash while switching mode (probably/possibly my fault?)

### ISSUE THREAD

**Issue by ajaelle12** [nicguzzo/wands#20]
Idk if I'm not supposed to add a crash support here but I'm just really confused. This only happens sometimes? Sorry if its just user error. :/

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 4/27/22, 3:02 PM
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1799.method_7909()" because "this.tools[i]" is null
	at net.nicguzzo.wands.Wand.do_or_preview(Wand.java:314)
	at net.nicguzzo.wands.ClientRender.render(ClientRender.java:207)
	at net.minecraft.class_863.handler$ejk000$render(class_863.java:522)
	at net.minecraft.class_863.method_23099(class_863.java:169)
	at net.minecraft.class_761.method_22710(class_761.java:1438)
	at net.minecraft.class_757.method_3188(class_757.java:1034)
	at net.minecraft.class_757.method_3192(class_757.java:813)
	at net.minecraft.class_310.method_1523(class_310.java:1122)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.nicguzzo.wands.Wand.do_or_preview(Wand.java:314)
	at net.nicguzzo.wands.ClientRender.render(ClientRender.java:207)
	at net.minecraft.class_863.handler$ejk000$render(class_863.java:522)
	at net.minecraft.class_863.method_23099(class_863.java:169)
	at net.minecraft.class_761.method_22710(class_761.java:1438)
	at net.minecraft.class_757.method_3188(class_757.java:1034)

-- Affected level --
Details:
	All players: 1 total; [class_746['__Aja__'/209, l='ClientLevel', x=857.79, y=65.00, z=-2248.22]]
	Chunk stats: 16384, 2664
	Level dimension: minecraft:overworld
	Level spawn location: World: (-16,63,531), Section: (at 0,15,3 in -1,3,33; chunk contains blocks -16,-64,528 to -1,319,543), Region: (-1,1; contains chunks -32,32 to -1,63, blocks -512,-64,512 to -1,319,1023)
	Level time: 19348 game time, 6517 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:407)
	at net.minecraft.class_310.method_1587(class_310.java:2376)
	at net.minecraft.class_310.method_1514(class_310.java:761)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, continuity/glass_pane_culling_fix, Mod Menu Helper.zip, continuity/default, BetterVanillaBuildingV2.71.zip

**Comment by r8420** [comment]
Also have this issue with FORGE 1.18.2 with version BuildingWands-2.4.1_mc1.18.2-forge.jar
