### ISSUE TITLE
Server Crashes due to Building Wands

### ISSUE THREAD

**Issue by YeahJustHi** [nicguzzo/wands#6]
**Server Crashed when going from a modded dimension to the overworld, not sure if there is a connection to the circumstances but I assume it would probably happen in other ways. I, and probably the others on my server do not have a wand as far as I know.**

**I am using Minecraft 1.17.1 and version 2.2.0 of Building Wands.**

**Here is the error:**

Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/minecraft/class_368
	at net.nicguzzo.wands.PlayerWand.add_player(PlayerWand.java:12)
	at net.nicguzzo.wands.WandsMod.process_keys(WandsMod.java:358)
	at net.nicguzzo.wands.WandsMod.lambda$init$9(WandsMod.java:108)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:151)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:788)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164)
	at net.minecraft.class_1255.method_16075(class_1255.java:125)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:770)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:764)
	at net.minecraft.class_1255.method_5383(class_1255.java:110)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:748)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:701)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_368
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at net.fabricmc.loader.launch.server.InjectingURLClassLoader.loadClass(InjectingURLClassLoader.java:57)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:175)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	... 16 more

**Comment by zISKo666** [comment]
Having the same crash with MC1.16.5 BW2.2.0 version too.

**Comment by nicguzzo** [comment]
What modded dimension is it? so I can test in the same conditions.

**Comment by nicguzzo** [comment]
I know what happened. I left some client code running on server side by mistake. I'll fix it right away

**Comment by nicguzzo** [comment]
fixed on version 2.2.1
